YOUNESS MOUAD (20 132 250)<br>
EL MAHDI ZOUHAIR (20 132 241)

In [1]:
import numpy as np
import GestionDonnees as gd

In [5]:
donnees = gd.GestionDonnees(True, False)

In [6]:
id_entrain, x_entrain, y_entrain, id_test, x_test = donnees.generer_donnees()

In [7]:
print(x_entrain)

[[-0.48661074 -0.13135701 -0.33095592 ... -0.39487147 -0.65214311
   0.26239707]
 [-0.58560191 -0.73488047 -0.02856115 ... -0.49497401  2.18166976
   0.13364087]
 [-0.58560191 -0.48340807 -0.48219201 ... -0.52001246  0.83564129
  -0.72463124]
 ...
 [-0.78358426 -0.63430181 -1.23821765 ...  0.1807566  -0.65214311
  -0.76756462]
 [-0.88257543 -0.73488047  0.5762671  ... -0.52001246 -0.51045972
  -0.72463124]
 [ 0.30542003 -0.23196142 -0.02856115 ...  0.08065405  1.18988604
   0.13364087]]


In [13]:
print(x_entrain)

[[0.007812 0.023438 0.023438 ... 0.004883 0.       0.025391]
 [0.005859 0.       0.03125  ... 0.000977 0.039062 0.022461]
 [0.005859 0.009766 0.019531 ... 0.       0.020508 0.00293 ]
 ...
 [0.001953 0.003906 0.       ... 0.027344 0.       0.001953]
 [0.       0.       0.046875 ... 0.       0.001953 0.00293 ]
 [0.023438 0.019531 0.03125  ... 0.023438 0.025391 0.022461]]
